### ISSUE TITLE
Server detected bot

### ISSUE THREAD

**Issue by cuong1014** [Joxroxagain/adidas-bot#10]
I'm try to run this code in adidas.com.vn but It isn't working, result always "Failed to cart shoe: temporary ban occured!". 

This is my config please let me know if I missing something:

{
    "url": "https://www.adidas.com.vn/en/yeezy",
    "taskCount": 1,
    "region": "VN",
    "splashMode": true,
    "headless": false,
    "headlessAfterSplash": false, 
    "splashCookieKeyword": "hmac",
    "webdata": {
        "enabled": false,
        "path": ""
    },
    "autoCart": {
        "enabled": true,
        "PID": "",
        "sizes": "4 UK,4.5 UK,6 UK"
    },
    "twocaptcha": {
        "enabled": false,
        "apiKey": "my 2captcha key"
    },
    "autoCheckout": {
        "enabled": true,
        "data": {
                Personal data...
        }
    },
    "retryDelay": 10000,
    "startUpDelayInterval": 10000,
    "detectionInterval": 1000,
    "alerts": true,
    "windowHeight": 800,
    "windowWidth": 1200
}

regions.js: { code: "VN", domain: "com.vn", language: "en" }

**Comment by Joxroxagain** [comment]
The bot no longer works and hasn't for a few months. I am not updating it anymore.
