### ISSUE TITLE
Automatic checkout error

### ISSUE THREAD

**Issue by Dam998** [Joxroxagain/adidas-bot#8]
Hi,
I have a problem when enabled automatic checkout, on submit request in the page with address form, the page refresh but adidas site redirects me to the same page (the page with the address form)
Do you know why? Do you have any ideas?

This is the error:
![errorAdidas](https://user-images.githubusercontent.com/23696659/70182946-273f4080-16e5-11ea-90ae-38a43345b1e9.png)

Thank you, the bot is so awesome

**Comment by DamianoPapi** [comment]
I have more informatio
Maybe this can be usefull to resolve the problem

![error1](https://user-images.githubusercontent.com/23696659/70186031-450fa400-16eb-11ea-9871-424dd4b43662.png)

![error2](https://user-images.githubusercontent.com/23696659/70186032-46d96780-16eb-11ea-9b2d-455a9373338b.png)

**Comment by Joxroxagain** [comment]
@DamianoPapi that has been happening since about a week after I added the auto checkout feature. They changed something in the checkout page and I briefly looked but didn't see anything obvious. I'm not planning to push any updated because I don't have much time and the splash page is not common anymore.

**Comment by sorxrob** [comment]
> I have more information
> Maybe this can be usefull to resolve the problem
> 
> ![error1](https://user-images.githubusercontent.com/23696659/70186031-450fa400-16eb-11ea-9871-424dd4b43662.png)
> 
> ![error2](https://user-images.githubusercontent.com/23696659/70186032-46d96780-16eb-11ea-9b2d-455a9373338b.png)

any updates on this?

**Comment by Joxroxagain** [comment]
@sorxrob Thanks for the post but I've already looked into all that information. Last I looked, they're changing the IDs on the page with every load and I lost interest a while ago. Sorry, but I won't be updating this repo anymore as I've moved on to other projects.

**Comment by sorxrob** [comment]
@Joxroxagain  Oh that's why. They have dynamic ID's already then. Thank you.
